Repository aternosgames/concepts, pull requests merged in 2018-12, with the labels that each got.

#16 added label.json to tools for github-label-manager
  tools/label.json
Labels: Category: Contributing, Status: Reviewed

#17 Add basic issue and pr templates (Fixes #13)
  github/templates/ISSUE_TEMPLATE/bug_report.md
  github/templates/ISSUE_TEMPLATE/code_style.md
  github/templates/ISSUE_TEMPLATE/feature_request.md
  github/templates/PULL_REQUEST_TEMPLATE.md
  github/templates/README.md
  github/tools/label.json
Labels: Category: Contributing, Category: General, Status: Reviewed, Type: Enhancement

#20 added readme template
  github/templates/README.md
Labels: Category: Contributing, Status: Waiting for review, Type: Feature request

#21 Fix some typos and grammatical mistakes
  .github/ISSUE_TEMPLATE/minigame-suggestion.md
  github/templates/ISSUE_TEMPLATE/code_style.md
Labels: Priority: Minor, Status: New, Status: Waiting for review, Type: Enhancement
